#!/usr/bin/env bash
# Bootstrap ~/study-journal/ for the study-session skill.
# Idempotent: safe to run multiple times. Will not overwrite user data.

set -euo pipefail

ROOT="${STUDY_JOURNAL_ROOT:-$HOME/study-journal}"

mkdir -p "$ROOT"
mkdir -p "$ROOT/books"
mkdir -p "$ROOT/evergreen"
mkdir -p "$ROOT/outputs"
mkdir -p "$ROOT/standalone/problems"
mkdir -p "$ROOT/standalone/arguments"

# .gitignore — never push book files (fair use is for personal learning)
if [ ! -f "$ROOT/.gitignore" ]; then
  cat > "$ROOT/.gitignore" <<'EOF'
# Book files — fair use for personal learning only, never push
*.epub
*.pdf
books/*/*.pdf
books/*/*.epub

# Local-only
.DS_Store
.obsidian/workspace*
.obsidian/cache
EOF
fi

# README — overview for the user
if [ ! -f "$ROOT/README.md" ]; then
  cat > "$ROOT/README.md" <<'EOF'
# Study Journal

Personal book learning notes generated by the `study-session` Claude Code skill.

## Structure

- `books/` — chapter-by-chapter notes, one file per chapter
- `evergreen/` — atomic principles extracted across chapters
- `outputs/` — composed artifacts (weekly reviews, exam prep, synthesis)
- `standalone/` — ad-hoc problems / arguments not tied to a book chapter
- `books.yml` — book metadata + progress

## Commands

- `/study-session` — start or resume a session
- Natural language: "ARQ Ch.5 같이 보자", "오늘 학습", "내 노트 검토", "복습 퀴즈"

## Convention

- Append-only chapter notes (don't edit prior session entries)
- Phase 3 (calibrate) requires a 30+ min delay from Phase 2 — same-sitting calibration is invalid
- Forms are auto-filled by the skill from session traces, not manually
- Closed-book recall is the only learning signal; self-report ("I got it") is not
EOF
fi

# books.yml — empty template, populated by skill on first session
if [ ! -f "$ROOT/books.yml" ]; then
  cat > "$ROOT/books.yml" <<'EOF'
# Books registered for study sessions.
# Skill populates this on first run; user can edit paths/types/parts directly.
#
# Schema:
# <slug>:
#   path: <absolute path to PDF>
#   format: pdf | epub-pending-conversion
#   type: methodology | problem-driven | conceptual | argument-driven | reference
#   parts: (optional, for books with sub-parts that need different types)
#     - id: <part-id>
#       type: <type>
#       pages: <range>
#   total_pages: <int>
#   printed_page_offset: <int>   # PDF page - printed page (front matter)
#   current_chapter: <id>
#   chapter_status:
#     <chapter-id>: in-progress | phase-2-complete | phase-3-pending | complete
#   chapter_metrics:
#     <chapter-id>:
#       closed_book_coverage: <0-1>
#       confidence_self_report: <0-100>
#       confidence_accuracy_gap: <int>
#       hint_levels: [<int>...]
#       avg_hint_level: <float>
#       avg_answer_length: <int>
#       transfer_attempt: success | partial | failure | domain-mismatch
#       session_count: <int>
#       session_health: { hint_abuse, illusion, surface, struggle_skip, form_fatigue, echo }
#   review_queue:
#     - { chapter: <id>, due: <YYYY-MM-DD>, type: 1d|1w|1m }

books: {}
EOF
fi

# Subdirectory _index files
for sub in evergreen outputs; do
  if [ ! -f "$ROOT/$sub/_index.md" ]; then
    cat > "$ROOT/$sub/_index.md" <<EOF
# $sub

Auto-generated index. The study-session skill maintains this file.
EOF
  fi
done

echo "study-journal bootstrapped at $ROOT"
echo ""
echo "Layout:"
echo "  $ROOT/"
echo "    README.md      .gitignore     books.yml"
echo "    books/         evergreen/     outputs/   standalone/"
echo ""
echo "Next: register books in books.yml (skill does this automatically on first session)."
